name: Maven CI

on:
  push:
    branches-ignore:
      - main

jobs:
  maven:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '22'
          cache: 'maven'

      - name: Compile with Maven
        run: ./mvnw compile verify

      - name: Test with Maven
        run: ./mvnw clean test